name: flutter_fic12_grocery_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  chuck_interceptor: ^2.0.9
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.3.2
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/tracking_mocukup.json
    - assets/images/
    - assets/images/banks/
    - assets/images/categories/
    - assets/images/products/
    - assets/icons/
