// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaWeEIucEkpG2E0DSKAoBaQ_AQgACIUwM',
    appId: '1:193922720160:web:9544e8277af397809584c5',
    messagingSenderId: '193922720160',
    projectId: 'fic-course',
    authDomain: 'fic-course.firebaseapp.com',
    storageBucket: 'fic-course.appspot.com',
    measurementId: 'G-B4X779GZ8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_KV1qBjFAYg7P4EtOR1MUvtFe4ELGAxo',
    appId: '1:193922720160:android:f1a5ac798f9d2a139584c5',
    messagingSenderId: '193922720160',
    projectId: 'fic-course',
    storageBucket: 'fic-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-kZ2oRjsixXFGEPZ498Kkvnb2LXYVJQ',
    appId: '1:193922720160:ios:8012f6b97352eb0d9584c5',
    messagingSenderId: '193922720160',
    projectId: 'fic-course',
    storageBucket: 'fic-course.appspot.com',
    iosBundleId: 'com.example.flutterFic12GroceryApp',
  );
}
